url: https://n4kz.com

cover: /static/img/cover.jpg

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - readme.md
  - license.txt
  - vendor

languages:
  - en
  - ru

sass:
  style: compressed
  sourcemap: never

markdown: kramdown
