title: >-
  Alexander Nazarov - Mobile App Developer

description: >-
  I'm Alexander Nazarov.
  I design and develop mobile applications and components

copyright: >-
  Copyright 2021, Alexander Nazarov. All rights reserved.
